### ISSUE TITLE
Standardized CI System Blog

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#1]
Create a tutorial on how/why we are using our standardized CI system.

This should also include:

- [x] Updating our standard CI system
- [X] Updating existing Journeys that are not using standardized CI
  * This will be an ongoing task
  * See below
- [x] Blog about how and why we are setting up our CI this way

### Complete and/or partially complete

- [x] [IBM/Kubernetes-container-service-GitLab-sample](https://github.com/IBM/Kubernetes-container-service-GitLab-sample)
  * https://github.com/IBM/Kubernetes-container-service-GitLab-sample/pull/50
- [x] [IBM/Scalable-Cassandra-deployment-on-Kubernetes](https://github.com/IBM/Scalable-Cassandra-deployment-on-Kubernetes)
  * https://github.com/IBM/Scalable-Cassandra-deployment-on-Kubernetes/pull/18
- [x] [IBM/Scalable-WordPress-deployment-on-Kubernetes](https://github.com/IBM/Scalable-WordPress-deployment-on-Kubernetes)
  * https://github.com/IBM/Scalable-WordPress-deployment-on-Kubernetes/pull/27
- [ ] [IBM/spring-boot-microservices-on-kubernetes](https://github.com/IBM/spring-boot-microservices-on-kubernetes)
  - [ ] Add new linters
    - [ ] JavaScript
    - [ ] Java

### Higher priority

- [x] [IBM/microservices-traffic-management-using-istio](https://github.com/IBM/microservices-traffic-management-using-istio)

### Lower priority

- [ ] [IBM/Cloud-Native-Workloads-on-LinuxONE](https://github.com/IBM/Cloud-Native-Workloads-on-LinuxONE)
- [ ] [IBM/container-journey-template](https://github.com/IBM/container-journey-template)
- [ ] [IBM/container-service-getting-started-wt](https://github.com/IBM/container-service-getting-started-wt)
- [ ] [IBM/container-service-gitlab-sample](https://github.com/IBM/container-service-gitlab-sample)
- [ ] [IBM/deploy-graph-db-container](https://github.com/IBM/deploy-graph-db-container)
- [ ] [IBM/GameOn-Java-Microservices-on-Kubernetes](https://github.com/IBM/GameOn-Java-Microservices-on-Kubernetes)
- [x] [IBM/Java-MicroProfile-on-Kubernets](https://github.com/IBM/Java-MicroProfile-on-Kubernetes)
  * https://github.com/IBM/Java-MicroProfile-on-Kubernetes/pull/19
- [ ] [IBM/k8s-service-accounts](https://github.com/IBM/k8s-service-accounts)
- [ ] [IBM/Microservices-deployment-with-PaaS-Containers-and-Serverless-Platforms](https://github.com/IBM/Microservices-deployment-with-PaaS-Containers-and-Serverless-Platforms)
- [ ] [IBM/OpenWhisk-on-Kubernetes](https://github.com/IBM/OpenWhisk-on-Kubernetes)
- [x] [IMB/resilient-java-microservices-with-istio](https://github.com/IBM/resilient-java-microservices-with-istio)
  * https://github.com/IBM/resilient-java-microservices-with-istio/pull/22
- [ ] [IBM/tensorflow-kubernetes-art-classification](https://github.com/IBM/tensorflow-kubernetes-art-classification)

**Comment by antonmc** [comment]
Please could you itemize the journeys too - checkbox style?

**Comment by mlangbehn** [comment]
@antonmc: will do.

**Comment by mlangbehn** [comment]
Draft of blog post is together, and I'm putting together an accompanying flowchart. I plan to post a draft to Medium later today.

**Comment by mlangbehn** [comment]
Draft of flowchart has been scribbled and sent to @antonmc for review.

**Comment by antonmc** [comment]
This needs to be reposted on the IBM Code site.
