### ISSUE TITLE
Standardized CD system

### ISSUE THREAD

**Issue by mlangbehn** [IBM/cloud-patterns-development#10]
## Brief description

Create a standard CD system for Journeys and write a tutorial on how/why we are doing it this way.

**Comment by mlangbehn** [comment]
I have started jotting down plans for this. Will reach out to @AnthonyAmanse to collaborate on this with one of his projects next week.

**Comment by mlangbehn** [comment]
Will be starting this with the work from @AnthonyAmanse's work in #42.

**Comment by mlangbehn** [comment]
While I was away working on #55, I believe this work was completed. I will set aside time today to get an answer on that and update accordingly.

**Comment by antonmc** [comment]
- [x] Evaluation of current state of CD system

**Comment by mlangbehn** [comment]
Currently, there are two different Toolchains setup, but both are using the same general process.

Git commit --> cf push
