### ISSUE TITLE
Visual Recognition with TensorFlow and OpenWhisk

### ISSUE THREAD

**Issue by loafyloaf** [IBM/cloud-patterns-development#103]
https://www.wrike.com/open.htm?id=195915853

This pattern describes how to recognize different flower types via an extended MobileNet TensorFlow model. The predictions are executed by TensorFlow running in an OpenWhisk function. The training is done on Kubernetes on the IBM Cloud.

**Comment by antonmc** [comment]
Check out kubeflow
