### ISSUE TITLE
Technology By and For People With Disabilities

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#104]
Let's write a blog post on this too.

**Comment by mlangbehn** [comment]
@antonmc and I will discuss in our meeting tomorrow.

**Comment by mlangbehn** [comment]
Published: https://medium.com/@roamingmatt/technology-by-and-for-people-with-disabilities-584de832b89a

**Comment by mlangbehn** [comment]
Published: https://developer.ibm.com/code/2018/02/14/technology-people-disabilities/
