### ISSUE TITLE
Verify ICP Vagrantfile

### ISSUE THREAD

**Issue by mlangbehn** [IBM/cloud-patterns-development#106]
@szihai asked me to take a look at the [ICP Vagrantfile](https://github.com/IBM/deploy-ibm-cloud-private/blob/master/Vagrantfile).

**Comment by jkomg** [comment]
This is what he said was happening: 

```
icp: You may need to change the 'base_segment' value in the 'Vagrantfile' to another subnet like '192.168.56'.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

As we saw in slack, his internal network is 192.168.1.x, so that shouldn't be the conflict.

**Comment by mlangbehn** [comment]
Here is a Gist of the vagrant deploy proceeding as expected: https://gist.github.com/mlangbehn/61c2f0dac3db96f4da420d2238fca03a

**Comment by mlangbehn** [comment]
In my testing thus far, I have not been able to reproduce this issue. @szihai mentioned to me late last night that there may be an issue with `vboxnet0` not being properly cleaned up after `vagrant destroy`.

I'll look into it and report back.

**Comment by mlangbehn** [comment]
**Note:** this may be related to IBM/deploy-ibm-cloud-private#53.

**Comment by mlangbehn** [comment]
Here is a Gist of vagrant provision failing (likely unrelated, but neat anyway): https://gist.github.com/mlangbehn/cebc33a2d8f64c8d6a72b014fa382368

**Comment by mlangbehn** [comment]
Here is a Gist of vagrant destroy followed by vagrant up: https://gist.github.com/mlangbehn/b70e1e95e38581891237a512a708be82

So far, I am not able to reproduce the issue.

**Comment by mlangbehn** [comment]
@szihai, can you verify the following information?
Answering directly below
*   Repo and commit you are deploying from?
https://github.com/IBM/deploy-ibm-cloud-private
*   VirtualBox version?
5.2.6
*   Vagrant version?
2.0.2
*   macOS version you are running?
10.13.3
*   Are there any other instances of ICP running on the machine? Other VMs? Containers?
Used to. Not when installing ICP
