### ISSUE TITLE
Drupal on Kube Pattern Completion

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#108]
https://github.ibm.com/IBMCode/IBMCodeContent/issues/925

**Comment by mlangbehn** [comment]
https://github.ibm.com/IBMCode/IBMCodeContent/issues/925

**Comment by mlangbehn** [comment]
* README updated
* Wiki first draft is up
* Architectural diagram needs to be converted from ASCII to PNG
