### ISSUE TITLE
Deploy Istio example to Bluemix Container Service

### ISSUE THREAD

**Issue by AnthonyAmanse** [IBM/cloud-patterns-development#11]
Existing docs in https://istio.io/docs/guides/bookinfo.html

**Comment by antonmc** [comment]
Please could you add a milestone?

**Comment by antonmc** [comment]
https://github.ibm.com/IBMCode/howtos

**Comment by AnthonyAmanse** [comment]
https://istio.io/docs/setup/ and https://istio.io/docs/guides/bookinfo.html
looks adequate for a how-to in deploying their example application in Bluemix Container Service.
