### ISSUE TITLE
Finish Kitura Pattern

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#116]
https://github.ibm.com/IBMCode/IBMCodeContent/issues/82

**Comment by antonmc** [comment]
Readme, blog and video need to be completed. Needs a few more days to complete.

**Comment by AnthonyAmanse** [comment]
copy pasting from IBM Code content issue 82
- [x] Create a thorough README.md https://github.com/IBM/kitura-on-kubernetes
- [x] Create CONTRIBUTING.md and MAINTAINERS.md
- [x] Add an Apache 2.0 license
- [x] Add an architectural diagram _in wiki/repo_
- [x] Create a blog http://developer.ibm.com/code/?p=38904&preview=1&_ppp=c7db717d11
- [x] Create a wiki to draft IBMCode content https://github.com/IBM/kitura-on-kubernetes/wiki
- [x] Add tests and CI
- [x] Create a video
