### ISSUE TITLE
Getting Started with IBM Cloud Private

### ISSUE THREAD

**Issue by loafyloaf** [IBM/cloud-patterns-development#12]
Introductory journey on getting started with IBM Cloud Private.  Includes Vagrantfile / Docker / etc to be able to install IBM Cloud Private on one or more VMs to represent a basic kubernetes cluster.

demonstrate the included apps/gui/etc.  We can then link back to this from existing container journeys to show how people can use/deploy to IBM Cloud Private as well as minikube/bluemix container service.

**Comment by antonmc** [comment]
Find a new owner for this repo. Couple of contributors - check the admins.
