### ISSUE TITLE
High Velocity Data Streams

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#123]
https://github.ibm.com/IBMCode/IBMCodeContent/issues/1013

**Comment by loafyloaf** [comment]
Update from the main board:
"Streams Designer has completed all work required for GDPR compliance and is awaiting an external penetration test (this has been a very long process that's currently in the procurement phase). We're hoping that the test will take place within the next few weeks after which we'll be able to re-enable the functionality."

**Comment by antonmc** [comment]
Pattern taken down until service available.

**Comment by loafyloaf** [comment]
penetration testing still in progress...

**Comment by antonmc** [comment]
Still testing.
