### ISSUE TITLE
94: Serverless web app with cloud storage

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#126]
This relates to internal issue:

https://github.ibm.com/IBMCode/IBMCodeContent/issues/94

**Comment by antonmc** [comment]
Assigning to @loafyloaf, since this is something he started a while back.

**Comment by loafyloaf** [comment]
working repository is here: https://github.com/loafyloaf/refarch-reviews
demo: https://loafyloaf.github.io/refarch-reviews/

- [x] Create a thorough README.md
- [x] Create CONTRIBUTING.md and MAINTAINERS.md
- [x] Add an Apache 2.0 license
- [x] Add an architectural diagram
- [x] Create a blog
- [x] Create a wiki to draft IBMCode content
- [x] Move to IBM org
- [x] Add tests and CI
- [x] Create a video

**Comment by antonmc** [comment]
John to follow up with Matt.
