### ISSUE TITLE
Serverless event stream processing (MessageHub integration)

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#127]
This relates to the content board item:

https://github.ibm.com/IBMCode/IBMCodeContent/issues/106

**Comment by loafyloaf** [comment]
1. [x] Move your code to IBM's github
2. [ ] Create a thorough README.md
3. [x] Create CONTRIBUTING.md and MAINTAINERS.md
4. [x] Add an Apache 2.0 license
5. [x] Add an architectural diagram
6. [x] Add tests and CI
7. [ ] Add Deploy to IBM Cloud support
8. [ ] Create a blog
9. [ ] Create a video
10. [x] Create a wiki to draft IBMCode content

**Comment by antonmc** [comment]
Limitations of open whisk - impacts the deploy button - manual steps. Needs feedback on this from whisk team.
