### ISSUE TITLE
151: Serverless mobile backend

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#128]
Relates to this content: https://github.ibm.com/IBMCode/IBMCodeContent/issues/151

**Comment by AnthonyAmanse** [comment]
note: use https://github.com/cloudant/CDTDatastore instead of https://github.com/cloudant/swift-cloudant

**Comment by AnthonyAmanse** [comment]
Services involved:
* Leverage GLB / DNS for custom domain (which svc?)
* cfx for dynamic content
* API GW front-ending cfx
* Cloudant to store data
* App Id for auth

Competitive ref point:
* https://s3.amazonaws.com/awslambda-reference-architectures/mobile-backend/lambda-refarch-mobilebackend.pdf

**Comment by AnthonyAmanse** [comment]
Services involved:
* Leverage GLB / DNS for custom domain (which svc?)
* cfx for dynamic content
* API GW front-ending cfx
* Cloudant to store data
* App Id for auth

**Comment by AnthonyAmanse** [comment]
Will do #139 instead (serverless data-at-rest processing)
