### ISSUE TITLE
Serverless image recognition

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#129]
Relates to: https://github.ibm.com/IBMCode/IBMCodeContent/issues/81

**Comment by AnthonyAmanse** [comment]
Possible architecture:
<img width="806" alt="architecture" src="https://user-images.githubusercontent.com/13695781/41944524-0ceb0740-795d-11e8-8605-edcab90e4191.png">

**Comment by AnthonyAmanse** [comment]
https://github.com/AnthonyAmanse/serverless-image-recognition/tree/initial-ios working on this branch

**Comment by AnthonyAmanse** [comment]
- [x] Create a thorough README.md https://github.com/IBM/serverless-image-recognition
- [x] Create CONTRIBUTING.md and MAINTAINERS.md
- [x] Add an Apache 2.0 license
- [x] Add an architectural diagram 
- [x] Create a blog
- [x] Create a wiki to draft IBMCode content
- [x] Add tests and CI
- [x] Create a video

**Comment by antonmc** [comment]
John will follow up with Matt.

**Comment by AnthonyAmanse** [comment]
moving back to develop. got feedback on https://github.ibm.com/IBMCode/IBMCodeContent/issues/81

**Comment by AnthonyAmanse** [comment]
Can be considered done (unless more feedback is provided)... Talked to publishing and should already be in their pipeline.
