### ISSUE TITLE
Update "Deploy Spring Boot microservices on Kubernetes" & "Manage microservices traffic using Istio" code patterns

### ISSUE THREAD

**Issue by AnthonyAmanse** [IBM/cloud-patterns-development#130]
https://github.ibm.com/IBMCode/IBMCodeContent/issues/1072
https://github.ibm.com/IBMCode/IBMCodeContent/issues/1074

**Comment by antonmc** [comment]
Spring boot part done.

**Comment by ykoyfman** [comment]
Will take a look at the update for issue 1074.

**Comment by antonmc** [comment]
1072 This one needs no new changes.
