### ISSUE TITLE
Multi Event Blockchain for CloudCoins

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#132]
There's enough interest in CloudCoins now to turn it into an on demand fabric. Each event could be an org on the fabric. We'd want blocks and records associated with each event. We'd want for people to be able to add their own new event, and for the apps to be able to lock to an event, either through choice or/and geo fencing. We'd want to run an ongoing virtual event that anyone in the world could join. At first we might want to restrict new events to IBM ones ... but eventually allow anyone to use the app anywhere, for their own event.

**Comment by antonmc** [comment]
Need to update hyperledger fabric and services, mongo database

**Comment by AnthonyAmanse** [comment]
Hyperledger fabric is using multiple channels - one channel for each event. Modified android app to use the multi-event blockchain

**Comment by AnthonyAmanse** [comment]
<img width="222" alt="screen shot 2018-08-20 at 1 46 16 pm" src="https://user-images.githubusercontent.com/13695781/44365788-9a388f80-a47f-11e8-9101-8195790eeb10.png">
<img width="222
" alt="screen shot 2018-08-20 at 1 46 23 pm" src="https://user-images.githubusercontent.com/13695781/44365815-ac1a3280-a47f-11e8-8b9f-c68cbd89ab6b.png">


<img width="222" alt="screen shot 2018-08-20 at 1 46 30 pm" src="https://user-images.githubusercontent.com/13695781/44365828-b4726d80-a47f-11e8-88b4-cf0eff904933.png">

**Comment by AnthonyAmanse** [comment]
Progress on iOS:
- [x] add in a selection dialog
- [x] multiple booklet
- [x] multiple registrations on blockchain channel
- [x] multiple leaderboard
- [x] multiple step tracking
- [x] multiple shop
- [ ] multiple push notification "tags" (android also needs this)

<img width="294" alt="screen shot 2018-09-03 at 9 20 15 pm" src="https://user-images.githubusercontent.com/13695781/45009869-5b4a2400-afbf-11e8-860d-4d08dfcd7c51.png">
<img width="294" alt="screen shot 2018-09-03 at 9 20 20 pm" src="https://user-images.githubusercontent.com/13695781/45009870-5b4a2400-afbf-11e8-9301-8821fa468ddc.png">

**Comment by antonmc** [comment]
Need to publish the iOS app.

**Comment by AnthonyAmanse** [comment]
published: https://play.google.com/store/apps/details?id=com.amanse.anthony.cloudcoins
