### ISSUE TITLE
Update Pattern - Resilient Java Microservices with Istio

### ISSUE THREAD

**Issue by AnthonyAmanse** [IBM/cloud-patterns-development#135]
Updated it to 0.8

Verify if it still works with 1.0 - _(same networking apis with 0.8)_

> pattern will be used by a developer advocate

**Comment by antonmc** [comment]
This corresponds to:

https://github.ibm.com/IBMCode/IBMCodeContent/issues/1108

**Comment by AnthonyAmanse** [comment]
Updated the Istio to 1.0
