### ISSUE TITLE
1169: API Connect Pattern for PetStore app

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#149]
https://github.ibm.com/IBMCode/IBMCodeContent/issues/1169#issuecomment-7547417

**Comment by loafyloaf** [comment]
The pattern author hopes to get Max (and myself?) access to API Connect the week of Sept. 17 (apparently blocked since Sept. 10)

**Comment by antonmc** [comment]
Needs a repo - underlying code - maybe work with their IBM Cloud org code base.

**Comment by antonmc** [comment]
Olaph will work directly with Sai on this.

**Comment by loafyloaf** [comment]
this is delayed until Dec
