### ISSUE TITLE
Explore GameOn Journey

### ISSUE THREAD

**Issue by AnthonyAmanse** [IBM/cloud-patterns-development#15]
Changes to Game-On application [gameontext/gameon](https://github.com/gameontext/gameon)
* Removed sidecar

Resolution:
* Try Istio

Links:
https://kubernetes.io/docs/concepts/services-networking/ingress
https://istio.io/
https://github.com/gameontext/gameon

**Comment by AnthonyAmanse** [comment]
Open issue in gameon repo: https://github.com/gameontext/gameon/issues/96

Use of istio

**Comment by antonmc** [comment]
This is a published pattern that is broken. Amalgam8 has merged with Istio ... so that broke the pattern. This has been time consuming to fix.

**Comment by AnthonyAmanse** [comment]
- [x] Built own images
- [x] Test on new cluster to make sure it works 
- [x] https://github.com/IBM/GameOn-Java-Microservices-on-Kubernetes/pull/35
- [ ] Add new CI structure

**Comment by jkomg** [comment]
I've had the associated Pattern pulled. If we get our workaround going, let me know.

**Comment by antonmc** [comment]
- [ ] held up by dependencies from original team

**Comment by antonmc** [comment]
Works in paid clusters. 

Needs to use ngx on k8s - unpaid clusters.

**Comment by antonmc** [comment]
- [ ] publish as is?
- [ ] discuss with Ozzy if this is ready to roll

**Comment by antonmc** [comment]
test out new scripts and helm charts
