### ISSUE TITLE
contribute to istio doc on mixer syntax

### ISSUE THREAD

**Issue by szihai** [IBM/cloud-patterns-development#16]
Write a tutorial as complimentary document on mixer rules

**Comment by szihai** [comment]
Needs decision on weather to keep the config files as repo or go with a blog.

**Comment by antonmc** [comment]
Waiting for feedback from the team in Israel

**Comment by antonmc** [comment]
This is published.

**Comment by antonmc** [comment]
https://medium.com/@szihai_37982/how-to-write-istio-mixer-policies-50dc639acf75

**Comment by stevemar** [comment]
@antonmc @szihai please port this over to the official place: https://github.ibm.com/IBMCode/howtos/
