### ISSUE TITLE
Pattern to highlight OpenJ9 performance characteristics  

### ISSUE THREAD

**Issue by ykoyfman** [IBM/cloud-patterns-development#165]
Investigate OpenJ9 characteristics with various workloads. Could be a pattern that tuning for different workloads (e.g. lower latency vs. memory footprint vs. startup time) and allows users to replicate experiments.  Perhaps include Java 11 features via OpenJDK (no-op gc in cloud environments?)

**Comment by antonmc** [comment]
John and @ykoyfman to schedule time to scope this.

**Comment by ykoyfman** [comment]
https://github.ibm.com/IBMCode/IBMCodeContent/issues/1954
