### ISSUE TITLE
1381: Securely connecting your on-premise resources with IBM Cloud Functions 

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#168]
https://github.ibm.com/IBMCode/IBMCodeContent/issues/1381

**Comment by antonmc** [comment]
Using secure gateway with on prem couch db.

**Comment by AnthonyAmanse** [comment]
published: https://developer.ibm.com/patterns/securely-integrate-serverless-functions-with-on-premises-resources/
