### ISSUE TITLE
Build a serverless starter kit in Node.js, Swift and Python

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#169]
https://github.ibm.com/IBMCode/IBMCodeContent/issues/1566

**Comment by loafyloaf** [comment]
Kits are complete, and publication material for a single code pattern presented for editing.

**Comment by loafyloaf** [comment]
this will be published as part of the main issue number, https://github.ibm.com/IBMCode/IBMCodeContent/issues/1566
