### ISSUE TITLE
Containerize an Application

### ISSUE THREAD

**Issue by AnthonyAmanse** [IBM/cloud-patterns-development#18]
Tutorial for making an app [Python, Java, Node, etc runtimes] use a container

* Making a Dockerfile
* Building the image
* Pushing into a repository

**Comment by antonmc** [comment]
Need more details - what is this? Why is it not covered elsewhere?

**Comment by szihai** [comment]
I think it's proposed before the docker 101 workshop material is prepared. Now it does seem like an overlap with the lab material.
