### ISSUE TITLE
Blog Post or Journey - personality insights and song lyrics

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#21]

**Comment by antonmc** [comment]
Adding a blog post to document my work for the conference presentation that I'm making. Maybe turn this into a journey? It runs on CF - a node app - I'd like to convert it to K8s.

**Comment by antonmc** [comment]
I also need to learn how to publish on IBM code.

**Comment by jkomg** [comment]
I should show you the IBM Cloud App service, it may be beneficial for this: 

https://console.bluemix.net/developer/appservice/dashboard
