### ISSUE TITLE
Rebuild monitoring infrastructure for IBM Developer

### ISSUE THREAD

**Issue by ykoyfman** [IBM/cloud-patterns-development#221]
- Alerts
- E2E live tests
- Deploy to multiple clusters behind load balancer

**Comment by gwgorman** [comment]
we already do all this on IBM Developer including a 2nd site in Oslo, a database cluster, load balancer & Akamai front end.

**Comment by gwgorman** [comment]
consider closing
oh and we have global probes and alerts through New Relic and use Pager Duty.

**Comment by loafyloaf** [comment]
superseded by #228
