### ISSUE TITLE
credit card serverless tutorial

### ISSUE THREAD

**Issue by loafyloaf** [IBM/cloud-patterns-development#232]
https://github.ibm.com/IBMCode/IBMCodeContent/issues/4630

**Comment by AnthonyAmanse** [comment]
https://github.com/AnthonyAmanse/openshift-serverless-nodejs-couchdb

**Comment by loafyloaf** [comment]
https://developer.ibm.com/tutorials//build-serverless-nodejs-applications-with-the-openshift-serverless-operator/
