### ISSUE TITLE
Transition from 'Loyalty' to 'Credit Card'

### ISSUE THREAD

**Issue by loafyloaf** [IBM/cloud-patterns-development#238]
Prepublishing:
- [x] updated diagram (requested [here](https://github.ibm.com/IBMCode/IBMCodeContent/issues/4634?#issuecomment-21519689) )
- [x] repo rename: example-bank

Publishing the changes to the credit card app will take some concerted effort - editor is [Tracy](https://github.ibm.com/tsulliva).  These changes will need to happen at the same time:
(Tracking in https://github.ibm.com/IBMCode/IBMCodeContent/issues/4634)

- [x] change `credit-card` fork of IBM/loyalty to `main`
- [x] update code pattern page
- [x] update tutorials (we can have this in one commit)

The question is: what do we then do with loyalty? Move it to a branch?
Option 1: completely overwrite it. dust off and nuke it from orbit. code pattern and tutorials have to be edited to reference new code.
Option 2: run loyalty and credit-card side by side. requires a duplicate set of code-pattern / tutorial pages. fork?

@antonmc sez: "Option 1 is what I've been asking for. As far as 'nuking' loyalty, just move it to a branch, put out to graze."

Other patterns can be published after the transition:
- [x] serverless
- [x] istio

**Comment by ykoyfman** [comment]
@loafyloaf  @AnthonyAmanse   We also have secrets whose names should be updated, along with corresponding YAMLs that set environment variables from the secrets.

```
$  [k|cc] #  oc get secrets | grep loyalty
loyalty-appid-secret                  Opaque                                2      37d
loyalty-db-secret                     Opaque                                5      37d
loyalty-iam-secret                    Opaque                                2      37d
loyalty-oidc-adminuser                Opaque                                2      37d
loyalty-oidc-secret                   Opaque                                4      37d
```

**Comment by ykoyfman** [comment]
https://github.ibm.com/IBMCode/IBMCodeContent/issues/4629:

1. Remove Loyalty references from https://developer.ibm.com/articles/intro-to-openshift-4/
2. Add new intro article about banking app.

**Comment by ykoyfman** [comment]
@loafyloaf @AnthonyAmanse @antonmc  FYI
https://github.ibm.com/IBMCode/IBMCodeContent/issues/4631 - Tekton (draft in progress)  Mon
https://github.ibm.com/IBMCode/IBMCodeContent/issues/4630 - serverless (draft available) 
https://github.ibm.com/IBMCode/IBMCodeContent/issues/4632 - threat modeling - update screenshots. 
https://github.ibm.com/IBMCode/IBMCodeContent/issues/4633 - service mesh (draft in progress) Weds?
**Operators Article - check for updating links to loyalty pattern. **
