### ISSUE TITLE
Summer Intern Project: Bee Travels Istio Code Pattern

### ISSUE THREAD

**Issue by ykoyfman** [IBM/cloud-patterns-development#242]
https://github.com/bee-travels/summer-project/issues/25
assigned to Grace

**Comment by loafyloaf** [comment]
maybe be pushlished as a 'Part I'

**Comment by loafyloaf** [comment]
https://github.ibm.com/IBMCode/IBMCodeContent/issues/4799

**Comment by loafyloaf** [comment]
published at: https://developer.ibm.com/components/istio/patterns/building-istio-service-mesh-for-microservices-app-on-kubernetes/
