### ISSUE TITLE
Investigate shared App Id for workshop

### ISSUE THREAD

**Issue by ykoyfman** [IBM/cloud-patterns-development#247]
From @GregDritschler 

The user erasure utility won't work with a shared appid service.  This utility was designed to make appid conform to the user registrations in a specific database.  Users not in that database will be removed from appid.  If you need to have a shared appid service, then perhaps you could somehow tie the appid user to a database instance  (maybe by recording something in the user profile) and have the utility restrict its processing to the users tied to the instance.  You would also have to consider whether a single appid user can be registered in multiple database instances and how the utility would deal with it.

**Comment by loafyloaf** [comment]
just thinking out loud here: the whole idea of the banking app is security. a lab that shows how to make it less so can't be a good idea

**Comment by loafyloaf** [comment]
will attendees have their own accounts?  they could each use their own free tier....
