### ISSUE TITLE
Add skills to Wrike

### ISSUE THREAD

**Issue by loafyloaf** [IBM/cloud-patterns-development#29]
Everyone needs to add their skills in Wrike

- [ ] Anton
- [x] Andy
- [x] Olaph
- [x] Matt
- [x] Anthony

**Comment by antonmc** [comment]
Where exactly in Wrike does this information need to go. I've seen kind of different lists, and tags in different places. Guidance?

**Comment by jkomg** [comment]
Let's schedule a quick screenshare, I can show you. Conversely, if people want to just list out their base skills, I can add them into Wrike and then people can just finish them up. 

Up to you folks.

**Comment by antonmc** [comment]
@mlangbehn - please set up a meeting for us to work through this ;)

**Comment by mlangbehn** [comment]
Chatted with @kennjason, who is going to update this issue in the coming days with a set of simple instructions for us to follow.

**Comment by jkomg** [comment]
If you go into Wrike, can you see this section: 

<img width="1498" alt="screen shot 2017-11-27 at 4 45 44 pm" src="https://user-images.githubusercontent.com/1976048/33293479-90eb12ea-d392-11e7-9bb3-6112dd0890c5.png">

in this section, each user is a "task" with associated tags. What I can do is add everyone and link them specifically here. 

What I'd like to see is a list of appropriate skills. You can use mine as a guide, just list your skillset here and I'll get them added. 

<img width="633" alt="screen shot 2017-11-27 at 4 48 38 pm" src="https://user-images.githubusercontent.com/1976048/33293589-f19249ce-d392-11e7-8d85-bf06d1e94c81.png">

Tagging: @antonmc @AnthonyAmanse @szihai @mlangbehn @loafyloaf

**Comment by jkomg** [comment]
We have two remaining folks to add skills before this is considered closed out. Can we get this done?
