### ISSUE TITLE
Deploy a Kitura Journey

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#30]
See wrike

**Comment by szihai** [comment]
The deployment of Kitura app to both K8s and CF is straightforward. To add SSL, it is a manual process via GUI.(For both self-generated openssl or Softlayer). There is no code change on the app.
Shall we turn this into a Howto?

**Comment by jkomg** [comment]
updated the pattern in wrike, the container service team would like us to proceed with this pattern as is. 

@szihai green light

**Comment by jkomg** [comment]
Suggestion for a nice tutorial (for developerworks and/or Bluemix blog): How to deploy a Kitura Web application using Bluemix Container Service *and* SSL (i.e. how to make the app available under a public ip/domain, add SSL certificate (e.g. from `let's encrypt` of from `IBM` if they provide SSLs)

**Comment by antonmc** [comment]
- here's a thing called Kitura ( and why we made and open sourced it )
- here's how to make a web app using Swift 
- here's how to secure it
- here's how to deploy to k8s
- here's how to deploy to cf

**Comment by antonmc** [comment]
https://console.bluemix.net/developer/appservice/starter-kits

**Comment by antonmc** [comment]
Decide on using the starter kit. It's fine if that makes it easier.

**Comment by jkomg** [comment]
this is the associated wrike entry: https://www.wrike.com/workspace.htm#path=folder&id=145457759&a=894735&c=board&ot=177563504&so=1&sd=0
