### ISSUE TITLE
OpenWhisk Podcast downloader

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#31]
wrike card: https://www.wrike.com/open.htm?id=169220204

**Comment by antonmc** [comment]
@loafyloaf Please can you add a url to the repo? And comment on the status of the video?

**Comment by antonmc** [comment]
https://github.com/loafyloaf/PodcastDownloader

**Comment by antonmc** [comment]
Original: https://github.com/IBM/PodcastDownloader

**Comment by loafyloaf** [comment]
https://github.com/IBM/PodcastDownloader/pull/1 gets the repo (mostly) ready for publication

**Comment by loafyloaf** [comment]
super rough rough draft video https://youtu.be/p8CoBhM-0Ck

**Comment by jkomg** [comment]
The editor has posted some comments on the blog post. Was that video published? I don't remember why I closed this >.<

https://github.ibm.com/IBMCode/PodcastDownloader/issues/4#event-19806805

@loafyloaf take a look at that please!

**Comment by loafyloaf** [comment]
The video is on youtube; I don't believe it is 'private' or anything: https://www.youtube.com/watch?v=95hDtAAzNnw

I've responded to (most of) the editors concerns.  One question this brings up: are included Components supposed to /only/ come from this list? https://pages.github.ibm.com/developer-journeys/journey-docs/dev/README/#components
