### ISSUE TITLE
Cassandra how-to on ICP

### ISSUE THREAD

**Issue by loafyloaf** [IBM/cloud-patterns-development#36]
Proposed as https://github.ibm.com/IBMCode/howtos/issues/84

**Comment by antonmc** [comment]
@kennjason - what is your expectation for this issue?

**Comment by jkomg** [comment]
I'm not sure I understand the question, the original issue is a howto for Cassandra on ICP, right? I don't have any expectations, if it turns out not feasible, scrap it.

**Comment by jkomg** [comment]
@antonmc ^^

**Comment by loafyloaf** [comment]
I have a draft up at https://github.ibm.com/mwagone/howtos/tree/cassandra-cluster-on-icp/cassandra-cluster-on-icp

**Comment by antonmc** [comment]
- [x] update with Steve's feedback and resubmit

**Comment by jkomg** [comment]
@loafyloaf has this been published?

**Comment by loafyloaf** [comment]
published: https://developer.ibm.com/code/howtos/cassandra-cluster-on-icp
