### ISSUE TITLE
updates to kubernetes patterns

### ISSUE THREAD

**Issue by paulczar** [IBM/cloud-patterns-development#37]
Update the following journeys to be more generic and support ICP.

* link to external install docs for each of minikube, BKS, ICP
* remove deploy-to-bluemix button as it doesn't make sense on a community facing repo.
* update CI to use minikube in travis.ci

- [x] https://github.com/IBM/Scalable-Cassandra-deployment-on-Kubernetes - [PR](https://github.com/IBM/Scalable-Cassandra-deployment-on-Kubernetes/pull/24)
- [x] https://github.com/IBM/Java-MicroProfile-on-Kubernetes - [PR](https://github.com/IBM/Java-MicroProfile-on-Kubernetes/pull/19)

- [x] https://github.com/IBM/Kubernetes-container-service-GitLab-sample 
- [x] https://github.com/IBM/Scalable-WordPress-deployment-on-Kubernetes
- [x] https://github.com/IBM/GameOn-Java-Microservices-on-Kubernetes
- [x] https://github.com/IBM/spring-boot-microservices-on-kubernetes
- [x] https://github.com/IBM/microservices-traffic-management-using-istio ( this might not be needed anymore, as [base journey includes istio](https://github.com/IBM/Java-MicroProfile-on-Kubernetes/pull/19) )
- [x] https://github.com/IBM/resilient-java-microservices-with-istio

**Comment by antonmc** [comment]
Make sure the ones that were promised are done - which ones are promised.

Cassandra, Java Micro Profile

**Comment by antonmc** [comment]
@loafyloaf - please look at these early ones for week 46

**Comment by jkomg** [comment]
This appears to have failed: https://travis-ci.org/IBM/Kubernetes-container-service-GitLab-sample/builds/283964519?utm_source=github_status&utm_medium=notification

@loafyloaf can you look into it? (I also pinged you on slack)

**Comment by jkomg** [comment]
I need the Gitlab one to pass, the others aren't pressing at this time (though we need them eventually)

**Comment by antonmc** [comment]
PR failed testing ... please fix the tests, verify and move this to closed.

**Comment by antonmc** [comment]
This is a priority

**Comment by loafyloaf** [comment]
ok - so that link is for a run of tests that happened about a month ago.  And the associated PR *did* merge.  Tests on the Gitlab repo are running fine, and have been passing solid for over a week now.

**Comment by jkomg** [comment]
The ICP instructions on that failed run never made it into the code tho.

**Comment by jkomg** [comment]
https://gph.is/2hJJ3Hf
