### ISSUE TITLE
Istio training material

### ISSUE THREAD

**Issue by szihai** [IBM/cloud-patterns-development#39]
Write and test the training material for Istio.

**Comment by szihai** [comment]
Move to week 46.

**Comment by antonmc** [comment]
Keeping this open to week 48 to reserve your time.

**Comment by szihai** [comment]
Based on the meeting on Nov 20th, there are 4 items to work on:
a.change the setup and exercise 1 to the context that the users have the cluster, but still need to download the bx cs cli and point Kubectl to the cluster.
b. Take out the volume part for mysql deployment.
c. Investigate the possibility of using compose-mysql service binding instead of mysql pod.
d. Add frontdoor ingress to both the guest service and telemetry services.
