### ISSUE TITLE
Building an indoor map database, with Node, Mongo, Mongoose & Kubernetes

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#42]
Create patterns that showcase popular IBM Cloud services: 

Cloudant NoSQL SB
SDK for Node.js
Liberty for java
Spring for java
Availability monitoring
compose for mongoDB - @antonmc has volunteered for this already
IoT platform @antonmc has stuff for this
Container registry: pipeline tools, CI/CD stuff (which we have) 

Notes: for DB ideas, maybe show off scale-out stateless API server containers, talking to a backend DB container?

**Comment by antonmc** [comment]
This one is going to be a part of the indoor map - map server - we'll define a set of JSON data to serve from Mongo. 

We want to be able to have multiple instances of the map. Some way of uploading new data easily.

- decide whether to use Mongo/Compose - or wrap it all up in a container - or describe both things - benefits and drawbacks.

- I can work with you to model the data.

**Comment by antonmc** [comment]
Let's use this journey for building the indoor map.

**Comment by antonmc** [comment]
@AnthonyAmanse are you able to create a repo for this - call it something like indoor-map-server ... we want a node runtime, and we want to expose some restful apis for retrieving indoor map data from a Mongo Database. I love using Mongoose with Mongo for ORM. So I think we want to pull that in too ... unless you think we should use Strongloop or API Connect or something else. Mongoose is simple and lovely.

**Comment by antonmc** [comment]
@AnthonyAmanse - we need to decide on whether to use Mongo within a container or from the Compose service ... what do you think?

**Comment by antonmc** [comment]
@AnthonyAmanse - we need to set up some kind of CI for this too - maybe we can get @mlangbehn involved if necessary - we want a dev version and production version, we're going to want unit tests

**Comment by antonmc** [comment]
I'll make a first pass of the JSON objects we want to work with.

**Comment by antonmc** [comment]
We'll want to write this up as a pattern, but this will serve as the map database for the secret map ... so can you find somewhere it can continue to run, and be reliable?

**Comment by antonmc** [comment]
how's this to start with for a json representation of a booth?

```
{ "unit":"npm",
  "description":"npm booth",
"measurement unit":"metre",
  "x-dimension":3,
"y-dimension":3,
"x":145,
"y":200,
"contact":"Jane Doe"}
```

**Comment by antonmc** [comment]
We'll want to cater for multiple events:

```
[{"event":"index",
"location":"san francisco",
"start date":"Feb 20, 2018",
"end date": "Feb 24, 2018",
"map":[{booth},{booth}]","beacons":[]},{"event":"think",
"location":"las vegas",
"start date":"March 20, 2018",
"end date": "March 24, 2018",
"map":[{booth},{booth}]"}, "beacons":[]]
```

**Comment by AnthonyAmanse** [comment]
@antonmc Mongo from the Compose service would make more sense if we'd want something ready for production

**Comment by antonmc** [comment]
We're going to want to serve the map dashboard from here too, so we'll need express at least.

**Comment by antonmc** [comment]
We'll also want another database of ibeacon locations - they'll work on the same chart axis as the booths.
```
{"beaconid":"QYUFIHGOE",
 "x":123,
"y":456,
"mincount":23,
"maxcount":400}```

part of the event object ( all of this is up for debate - I'm suggesting this to start with )

**Comment by antonmc** [comment]
Examples with mongoose - https://github.com/antonmc/insurance-bot

**Comment by AnthonyAmanse** [comment]
Working on the backend here https://github.com/AnthonyAmanse/kubernetes-mongoose
