### ISSUE TITLE
Re-do of flagship Istio pattern

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#44]
We should be able to do something better for our flagship Istio pattern than bookinfo. That was made under duress and time constraints. We should instead create a pattern on Istio using an IBM Cloud service like Watson as egress, with specific config. Perhaps something about security with Istio, or traffic management (which @szihai explored some already). Maybe leveraging Armada Front Door + Istio? 

Lin is going to write up more for @antonmc

**Comment by szihai** [comment]
The capability of Watson on traffic detection is unknown. We should investigate (work with the Watson team) first.  If it works, we can write an adapter to Watson backend.
