### ISSUE TITLE
Kube 101 Demo App to How-To

### ISSUE THREAD

**Issue by AnthonyAmanse** [IBM/cloud-patterns-development#48]
Coffee Application - Horizontal Pod Autoscaling with Kubernetes
https://github.com/AnthonyAmanse/kubernetes-starter-coffee-app

https://github.ibm.com/IBMCode/howtos

**Comment by AnthonyAmanse** [comment]
https://github.ibm.com/IBMCode/howtos/issues/81 looks like someone is already on an Autoscaling How-To

**Comment by stevemar** [comment]
@AnthonyAmanse i would love your expert feedback on the issue and PR (when it comes up)

**Comment by antonmc** [comment]
Should we defer this task?

**Comment by AnthonyAmanse** [comment]
@stevemart will do
