### ISSUE TITLE
Deploy a Serverless Multilingual Conference Room

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#49]
https://www.wrike.com/workspace.htm#path=folder&id=145457759&p=145426675&a=894735&c=board&ot=189917941&so=1&sd=0

This journey proposes a method to create a communications channel that’ll allow clients who speak different languages to seamlessly communicate with each other. This can be particularly useful in meetings rooms and conference calls where the participants are located in different countries, as translated subtitles or audio can be generated and delivered in real time. 

This leverages the MQTT messaging protocol, which allows for each client to publish and “subscribe” to one or more channels. The channel makeup determines each client’s requested language and payload type, (fromClient/french/audio, for example). 

The channel that each submitted message is sent to determines the sequence of cloud functions that will be called; for example, submitting a message to fromClient/english/audio will run the audio payload through Watson’s speech to text service, forward that result to the translation service, and then distribute the translated result to all listening clients

**Comment by jkomg** [comment]
For this one, we want to work with Steve's team as it's both serverless and watson.

**Comment by jkomg** [comment]
@loafyloaf most of this is done and we need access to the repo, but do you feel like this is something you can finish up for week 48?

**Comment by loafyloaf** [comment]
I will speak with Steve about collaboration, and report back with a better timeline for publication

**Comment by loafyloaf** [comment]
Steve's team is too busy to help out.  I am working with the creator directly.  I think we can get a working demo to publish along with this pattern.  Week 4?

**Comment by antonmc** [comment]
Action: Get in touch with Watson team originators - host in IBM code. Minimally refer to the original work in the description or README.

**Comment by antonmc** [comment]
TODO: @kennjason - get this ready for publishing please

**Comment by jkomg** [comment]
@loafyloaf Can you link the artifacts necessary for publication? Blog, wiki etc

**Comment by jkomg** [comment]
moved to validate in wrike; OM docs & pdf's generated

**Comment by antonmc** [comment]
in publishing
