### ISSUE TITLE
Building Serverless Web Applications with OpenWhisk

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#50]
This project shows how to write (Angular) web applications which use OpenWhisk actions to implement backend logic. Users need to log in with their Google accounts via OAuth. After this users can access OpenWhisk actions that have been protected via OpenWhisk API management.

There are other journeys/samples which go in the same direction, but this one is the only one that shows how to authenticate users via OAuth and how to use the built-in API gateway to manage access.

https://www.wrike.com/workspace.htm#path=folder&id=147077122&p=147077017&a=894735&c=board&ot=169826323&so=1&sd=0

**Comment by jkomg** [comment]
@szihai to work with dev to modify the readme for intention and scope

**Comment by szihai** [comment]
README ready.

**Comment by antonmc** [comment]
- [ ] Needs Wiki
- [ ] Needs Diagram

**Comment by szihai** [comment]
- [x]  Wiki
- [x]  Diagram

**Comment by szihai** [comment]
Waiting on the author to provide a blog.

**Comment by szihai** [comment]
Blog: http://developer.ibm.com/code/?p=30720&preview=1&_ppp=4170934a98

**Comment by jkomg** [comment]
@szihai this looks a preview. has it been vetted? is it published?

**Comment by szihai** [comment]
@kennjason please move the card in Wrike. I don't think Niklas will enrich it any more.

**Comment by jkomg** [comment]
moved back to in-progress, Andy please incorporate Niklas's changes and ping here when complete.

**Comment by jkomg** [comment]
@szihai ^^

**Comment by antonmc** [comment]
Istio and front door ingress problem fixes.
