### ISSUE TITLE
java microprofile config

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#56]
https://www.wrike.com/workspace.htm#path=folder&id=145457759&a=894735&c=board&ot=182142377&so=1&sd=0&sq=undefined

This is a Pattern that Paul was working on with BJ Hargrave, it looks like the work is done sans some QA and the blog post. BJ may be interested in writing the blog post, I'm looking into it.

**Comment by jkomg** [comment]
code is here: https://github.com/IBM/java-microprofile-config
blog is here: https://github.com/IBM/java-microprofile-config/wiki/Blog

just need QA

**Comment by mlangbehn** [comment]
QA:
   - [X] Blog
      * Added small revisions
         * https://github.com/IBM/java-microprofile-config/wiki/Blog/_history
   - [X] Code
      1. Cloned repo
      2. Ran steps
      3. Verified links

**Comment by mlangbehn** [comment]
Sent to publishing

**Comment by mlangbehn** [comment]
Published.

**Comment by loafyloaf** [comment]
link to published pattern: https://developer.ibm.com/code/patterns/configure-your-app-using-eclipse-microprofile-config/
