### ISSUE TITLE
Indoor map pattern 

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#57]
Document the pattern for kubernetes/mongo/mongoose ... take the work you did for the implementing the map and do the work to turn it into a pattern.

**Comment by AnthonyAmanse** [comment]
https://github.com/IBM/secret-map-dashboard

**Comment by AnthonyAmanse** [comment]
https://github.com/IBM/kubernetes-mongoose is the repo for the pattern.

Working on the README on this fork
https://github.com/AnthonyAmanse/kubernetes-mongoose-1/tree/add-pattern-readme

**Comment by AnthonyAmanse** [comment]
- [x] Architecture diagram

- [x] Flow - add in readme with the architecture diagram

- [x] Add in necessary markdown files such as `CONTRIBUTING` and `MAINTAINERS`

- [x] Wiki / Journey Page

- [x] Blog

**Comment by jkomg** [comment]
jason to create an OM repo for this and add it to wrike.

**Comment by AnthonyAmanse** [comment]
Moving this back to in progress as the pattern isn't published yet

**Comment by antonmc** [comment]
- [ ] SVG versions
- [ ] Split out into its own repo

**Comment by antonmc** [comment]
think it's ready - no video yet

**Comment by jkomg** [comment]
@AnthonyAmanse I need to write some OM docs for this Pattern, can you answer a few questions for me? 

Contact information
Name

Email

Journey Summary
Brief Description of Journey

Your Job Function and Business Unit


Provide links to the Journey, its code, and collateral

Detailed Journey Proposal Description ( aka What is it? )

Who is it for? ( Example: “Python developers working at retail companies who are looking into chatbots” )

What problem does it solve for developers?

**Comment by jkomg** [comment]
This pattern is on the Content board: https://github.ibm.com/IBMCode/IBMCodeContent/issues/428
