### ISSUE TITLE
Backend for scraping reviews

### ISSUE THREAD

**Issue by AnthonyAmanse** [IBM/cloud-patterns-development#59]
https://github.com/IBM/watson-review-analyzer

**Comment by AnthonyAmanse** [comment]
Pattern is due in February. The pattern is part of the SLAM Project

**Comment by AnthonyAmanse** [comment]
https://github.com/IBM/watson-review-analyzer/pull/8
- add Cloudant feature

**Comment by antonmc** [comment]
This is a duplicate - closing
