### ISSUE TITLE
Hello world with akka ( 101 Journey )

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#67]
Use the Akka-provided quickstart to demonstrate a basic akka app

https://github.com/akka/akka-quickstart-java.g8

http://developer.lightbend.com/guides/akka-quickstart-java/

**Comment by szihai** [comment]
- [x] Code repo and README

- [x] Architecture diagram

- [x] Flow 

- [x] Wiki / Journey Page

- [x] Blog

**Comment by szihai** [comment]
The blog draft: http://developer.ibm.com/code/?p=29423&preview=1&_ppp=318c8ecf52
The code repo plus wiki:https://github.com/IBM/Akka-cluster-deploy-kubernetes

**Comment by antonmc** [comment]
Ready to be sent to publishing team

**Comment by szihai** [comment]
@kennjason Please move the wrike card to Validate.

**Comment by jkomg** [comment]
This was kicked back to us for not complying with IBM Code style guidelines, just ping me here when it's completed. Moved back into in progress

**Comment by szihai** [comment]
Hi @kennjason , I think you confused two similar patterns. The one I was working on is https://github.com/IBM/Akka-cluster-deploy-kubernetes. I noticed in Wrike it was not moved. So today I moved it to "validate" and it's the only one in that column.

For this pattern: https://github.com/IBM/akka-react-cloudant, It's my first time looking at it. But I  fixed the wiki anyways. Still the author needs to provide a blog.

**Comment by jkomg** [comment]
@szihai 

So it looks like this is the one that needs the wiki to be done up with IBM Code template: https://www.wrike.com/workspace.htm#path=folder&id=145457759&p=145426675&a=894735&c=board&ot=185536060&so=1&sd=0

the other: https://www.wrike.com/workspace.htm#path=folder&id=145457759&p=145426675&a=894735&c=board&ot=169826323&so=1&sd=0
is the one that Niklas has been quiet on. 

You're currently working on the first at this point and were waiting on blog post from Niklas on the second, is that correct?

**Comment by szihai** [comment]
@kennjason , The wrike item corresponds to this tile (#67) is :https://www.wrike.com/open.htm?id=172664332 
**However** this wrike item is not showing up under "_Journey status" but only under "CI".
This pettern has been done. The Git repo is:
https://github.com/IBM/Akka-cluster-deploy-kubernetes
Wiki is:
https://github.com/IBM/Akka-cluster-deploy-kubernetes/wiki
And blog is:
http://developer.ibm.com/code/?p=29423&preview=1&_ppp=cca7428f18


For wrike item https://www.wrike.com/workspace.htm#path=folder&id=145457759&p=145426675&a=894735&c=board&ot=185536060&so=1&sd=0, there is no tile yet on this board. Please create one for it.
I have updated the wiki: https://github.com/IBM/akka-react-cloudant/wiki
The blog has just been finished today: http://developer.ibm.com/code/?p=30443&preview=1&_ppp=506530f7b5
Only thing left is to fix the README a little. https://github.com/IBM/akka-react-cloudant

And these are the 2 AKKA patterns.
The Openwhisk on is still waiting for Niklas to finish the blog.
