### ISSUE TITLE
Improve istio lab

### ISSUE THREAD

**Issue by szihai** [IBM/cloud-patterns-development#69]
There are 2 main questions people ask during the istio lab on Dec 5 ,2017:
a. How does Envoy work? How is it different from Kube Proxy?
b. How to do Authorization and tls for traffic between pods?
To better showcase the advantages of Istio, it is better to modify the lab to:
1. Replace the lab 4 with showing how K8s LB works and change lab 6 to compare with lab 4. An enhancement  is to show the traffic pattern difference.
2. Add lab 11 to showcase TLS and RBAC in pod traffic. Better to show a compromised pod cannot reach to other pods with TLS and RBAC enabled (and was able to without the features).

**Comment by jkomg** [comment]
@szihai - I think an important piece of this that I need is the Istio workshop re-worked to fit into a standard meetup environment, which I think is separate from the additions above. I'm thinking the meetup aspect needs a new task.

**Comment by jkomg** [comment]
What I'm looking for is: 

1. How would we break this workshop into smaller, consumable pieces?
2. It's an interactive workshop; can we make it into a presentation instead?

**Comment by szihai** [comment]
@kennjason There are ways to make it interactive and modular. For example, [katacoda](https://www.katacoda.com/) is a platform for interactive courses. The advantage of using it is it solves logistic problems which is a huge bottleneck.

**Comment by jkomg** [comment]
@szihai what I'm saying is the original lab is interactive and great, what we want from it is chunks that can be presented at a meetup that isn't a lab, just a presentation. 

Can you do that?

**Comment by szihai** [comment]
@kennjason ,eh, I don't think the lab material is a good candidate for presentation. I have filtered through my collection of slides and found a couple fairly good ones. If you want I can polish and consolidate them into a deck of ~ 20 slides.

**Comment by jkomg** [comment]
@szihai so do we have consensus on what needs to be done for this item?

**Comment by szihai** [comment]
@kennjason I think so. I will divide the lab into around 20 slides.
