### ISSUE TITLE
ensure CI Patterns are in existing CI/CD 

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#72]

**Comment by AnthonyAmanse** [comment]
Going to list the existing patterns here
Data from wrike

**Standard CI**
- [x] [Make Java microservices resilient with Istio](https://github.com/IBM/Java-MicroProfile-Microservices-on-Istio) _Using Standard CI_
- [x] [Deploy Spring Boot microservices on Kubernetes](https://github.com/IBM/spring-boot-microservices-on-kubernetes) _Using Standard CI_
- [x] [Run GitLab on Kubernetes](https://github.com/IBM/kubernetes-container-service-gitlab-sample) _Using Standard CI_
- [x] [Deploy a scalable WordPress implementation on Kubernetes](https://github.com/IBM/scalable-wordpress-deployment-on-kubernetes) _Using Standard CI_

**Repo has Own CI**
- [x] [Deploy a scalable Apache Cassandra database on Kubernetes](https://github.com/IBM/Scalable-Cassandra-deployment-on-Kubernetes) _Using Standard CI (using minikube)_
- [x] [Deploy MicroProfile-based Java microservices on Kubernetes](https://github.com/IBM/Java-MicroProfile-on-Kubernetes) _Using Standard CI (using minikube)_
- [x] [OpenChecks](https://github.com/IBM/openchecks) _Repo has own CI_
- [x] [Building the NFL RedZone for eSports](https://github.com/IBM/rotisserie) _Repo has own CI_
- [x] [Manage microservices traffic using Istio](https://github.com/IBM/Microservices-with-Istio-Service-Mesh-on-Kubernetes) _Repo has own CI_
- [x] [Create a hybrid cloud with API Connect and Secure Gateway](https://github.com/IBM/Hybrid-Cloud-Applications-and-Services) _Repo has own CI_
- [x] [Deploy Java microservices on Kubernetes with polyglot support](https://github.com/IBM/GameOn-Java-Microservices-on-Kubernetes) _Repo has own CI_ **Pattern pulled**
- [x] [Respond to Messages and Handle Streams](https://github.com/IBM/openwhisk-data-processing-message-hub) _Rep has own CI_
- [x] [Build serverless API handlers](https://github.com/IBM/openwhisk-serverless-apis) _Repo has own CI_
- [x] [Create autoscaling actions that respond to database](https://github.com/IBM/openwhisk-data-processing-message-hub) _Repo has own CI_

**No CI**
- [ ] [API in 5 minutes](https://github.com/IBM/loopback-in-five) _No CI_
- [ ] [Transform the retail customer experience with APIs on a mainframe](https://github.com/IBM/increase-retail-revenues-leveraging-hybrid-cloud-on-mainframes) _No CI_
- [ ] [Run cloud-native workloads on a Linux mainframe](https://github.com/IBM/Cloud-Native-Workloads-on-LinuxONE) _No CI_
- [ ] [Boost insight by moving analytics closer to data](https://github.com/IBM/Spark-on-zOS) _No CI_
- [ ] [Turn your mainframe into an API powerhouse](https://github.com/IBM/Restful-APIs-using-zOS-Connect) _No CI_
- [ ] [Create financial applications using APIs on mainframe](https://github.com/IBM/Banking-digitalization-using-hybrid-cloud-with-zSystem) _No CI_
- [ ] [Apply machine learning to financial risk management](https://github.com/IBM/Financial-risk-management-using-machine-learning-on-zSystems) _No CI_
- [ ] [API Connect - ACME Freight](https://github.com/ibm/acme-freight) _No CI_
- [ ] [[Acme Freight] Unlock Data With APIs Part II - OpenWhisk](https://github.com/ibm/acme-freight) _No CI_
etc
