### ISSUE TITLE
Node.js on Z/OS - Create rewards program APIs and deploy on Z/OS

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#77]
Using Node.js to create your backend application and generate the set of APIs for your enterprise. Deploy the application on z/OS for best performance and security.

https://www.wrike.com/workspace.htm#path=folder&id=147077122&p=147077017&a=894735&c=board&ot=191115025&so=1&sd=0

https://github.com/ibmruntimes/loopback-demo-zos

n this developer journey, we build a Node.js backend application on z/OS. The application accesses information that resides on z/OS and provides an API that can later be consumed by frontend applications and services. This tutorial highlights the benefits of hosting the Node.js application on z/OS and introduces Node.js development for traditional z/OS developers.

Node.js on z/OS is a first-class enterprise offering, making it ideal for hosting backend applications that require access to z/OS assets, while providing performance, scalability and security. In this developer journey, we showcase the business challenges that a typical customer on IBM Z might experience. We share a case study about a fictitious TorCC credit card company, and how they leverage the capabilities of both Node.js and z/OS. At the end of this developer journey, you will have created your own Node.js application with the Loopback framework, and deployed it on z/OS.

**Comment by jkomg** [comment]
@loafyloaf is this something you think you can pull off next week? Can you take a look at it and see? My understanding is most of the work is done, but Iris will probably also be available for pairing on it if need be. This is the one I mentioned in retrospective today.

**Comment by loafyloaf** [comment]
This pattern is pretty much ready to go.  Iris is planning a blog post, but it will not be ready until early next week.  We also need to get the repo into the IBM namespace - I've written to her about this, but it hasn't happened yet.

**Comment by antonmc** [comment]
-  The Z team is writing a blogpost
-  @kennjason needs to create the OM docs
-  Repo needs to be moved to IBM GitHub org
