### ISSUE TITLE
make Kelsey's Kubecon keynote work on IBM Cloud

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#81]
https://www.youtube.com/watch?v=07jq-5VbBVQ

specifically we want CI/CD without needing to access kubectl commands, if we can. Can we?

**Comment by mlangbehn** [comment]
@kennjason: To sum up my notes to discuss with you about the Keynote:

*   Yes, we can and should have development environments, CI, and CD working without developers ever needing to touch kubectl
*   With our specific use cases, I disagree with Kelsey's usage of separate deployment repositories (in his Keynote, he proposes using three separate repositories)
*   If we opt for pull requests as a final gate for deployment, we can implement that, but I have found that better testing and reviewing earlier in the process is more efficient

**Comment by jkomg** [comment]
@mlangbehn: Perfect! Can you map out what that story would look like and how it would work?

**Comment by jkomg** [comment]
@mlangbehn I'm also interested in how your view differs from Kelsey in this case and why.

**Comment by mlangbehn** [comment]
@kennjason: What do you mean by map out? Do you want a flow chart, or outline, or what?

I can take this on when I get back from my customer engagement or I can provide guidance in my downtime until then.

**Comment by mlangbehn** [comment]
@kennjason: Just wanted to touch base with you, now that I am back.

**Comment by jkomg** [comment]
I think with the work we've got cooking to explore CI/CD, we don't need to do this separately. I think too long has gone by for this to be as relevant and we don't want to be too much of a "me too" with this. 

Unless you have work already on this or see a reason to keep it, I'm going to go ahead and close this issue down. 

@mlangbehn
