### ISSUE TITLE
Create event tracking form (or at the variables) for eventboard

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#83]
Work with marketing and product to create an end to end form to use for tracking events that we can implement for eventboard

**Comment by antonmc** [comment]
- [ ] need input from marketing on what is needed

**Comment by jkomg** [comment]
Event tracking prototype: https://github.ibm.com/developer-journeys/eventboard/blob/master/.github/issue_template.md

Form is based on input from: https://ibm.box.com/s/x946l7ttajhx2dk4xc9atn1vu67zete1

Still to do: 

1. Add in additional deliverables from product and marketing teams.

**Comment by jkomg** [comment]
Liz and I pitched eventboard to Michael and Manny, and it looks like this is something that can be worked on after we complete work with incubator.

**Comment by jkomg** [comment]
moved to week 8, this is a work in progress
