### ISSUE TITLE
Istio Workshop for Index

### ISSUE THREAD

**Issue by antonmc** [IBM/cloud-patterns-development#85]

**Comment by szihai** [comment]
Based on the meeting of Jan 29th, for week 6, the things to do are:
add Mutual TLS excercise.
add Front door exercise.

**Comment by duglin** [comment]
@szihai can we get more info about this? Is this a formal Index session?

**Comment by szihai** [comment]
@duglin , yes it is a workshop on the first day Feb 20th. The material is based on the Kubecon workshop with some changes. Currently the Mutual TLS and IBM Front door will be added. Some other changes are pending on the release date of Istio 0.5 and Armada K8s 1.9.
