### ISSUE TITLE
Visual Recognition with Tensorflow and Openwhisk

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#87]
https://www.wrike.com/workspace.htm#path=folder&id=145457759&p=145426675&a=894735&c=board&ot=195915853&so=1&sd=0

This pattern seems to be complete, it needs to be formatted as a pattern, etc.

**Comment by szihai** [comment]
If that's ready can we get him to go through the self-serving Incubator pipeline?

**Comment by jkomg** [comment]
I wish I could say yes, but not currently. 

What I will say is there isn't a rush on this one yet, so we can wait and see how things turn out next week (there's a strong of meetings in SF). 

Hang tight.
