### ISSUE TITLE
Combining Akka and React and Cloudant

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#91]
https://www.wrike.com/workspace.htm#path=folder&id=145457759&a=894735&c=board&ot=185536060&so=1&sd=0

@szihai since you just completed an akka pattern, can you get this one out of the way? It looks like most of the work is done, it's formatting issues.

**Comment by szihai** [comment]
Done

**Comment by szihai** [comment]
@kennjason the README has been updated. Wiki and blog as well.

**Comment by jkomg** [comment]
Where is the blog?

**Comment by szihai** [comment]
@kennjason , the blog is https://developer.ibm.com/code/?p=30443&preview=1&_ppp=506530f7b5

**Comment by jkomg** [comment]
@szihai can you look at Clyde's recommendations for the overview as well?
