### ISSUE TITLE
Porting your python, java or node apps to a serverless runtime

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#96]
https://www.wrike.com/workspace.htm#path=folder&id=145457759&a=894735&c=board&ot=166018730&so=1&sd=0

Many developers are interested in the benefits of serverless development: Speed of deployment, reduced operational concerns, autoscale, and fine-grained cost for resource usage. However, there is a chasm to cross in terms of understanding the serverless programming model. One way to bridge this gap is to support traditional web frameworks on top of a serverless deployment model.

Putting this in the backlog for now, there's a host of serverless pattern potentials and this is one of the oldest.

**Comment by antonmc** [comment]
This one too nebulous right now ... we need a story and some creative code. @kennjason - please talk to Daniel about this.
