### ISSUE TITLE
Improving Github project functionality with Cloud Functions

### ISSUE THREAD

**Issue by loafyloaf** [IBM/cloud-patterns-development#98]
adapt incubator use case into a pattern / presentation

**Comment by loafyloaf** [comment]
ready as write item: https://www.wrike.com/open.htm?id=212649433

**Comment by antonmc** [comment]
- [x] video
- [x] blog post
- [x] wiki
- [x] readme

**Comment by antonmc** [comment]
CI and CD open whisk functions
