### ISSUE TITLE
Creating a Lagom service to integrate with Websphere Liberty via IBM Message Hub

### ISSUE THREAD

**Issue by jkomg** [IBM/cloud-patterns-development#99]
https://www.wrike.com/workspace.htm#path=folder&id=145457759&p=145426675&a=894735&c=board&ot=203332487&so=1&sd=0

This project demonstrates a simple service that integrates with the IBM Message Hub Kafka Liberty sample application. The source code demonstrates how to write a Lagom service that can both consume messages produced by the Liberty sample application, and produce messages that can be consumed by it. You can run the service in a local development environment, a local Kubernetes cluster created using Minikube, or in the cloud using IBM Bluemix Container Service.

**Comment by antonmc** [comment]
- [ ] wiki
- [x] repo created
- [ ] diagram
- [ ] blog
- [ ] icp

**Comment by antonmc** [comment]
This is waiting on something that Matt was to look at.

**Comment by antonmc** [comment]
vagrant file problems

**Comment by antonmc** [comment]
Moved to the code content board https://github.ibm.com/IBMCode/IBMCodeContent/issues/73
